[package]
name = "aurora"
version = "0.1.0"
authors = ["Dale <putnam.dale17@gmail.com>"]
publish = false

[dependencies]
nalgebra = "0.23.0"
rlua = "0.17.0"
image = "0.19.0"
num_cpus = "1.8.0"
failure = "0.1.1"
rand = "0.8.3"
thread_local = "1.1.3"
clap = "~2.33.3"